from sklearn.metrics import cohen_kappa_score
annotator_1 = [
   "Clarification snippet of code",
    "Clarification snippet of code",
    "Clarification snippet of code",
    "Clarification snippet of code",
    "Summary Request",
    "Clarification snippet of code",
    "Summary Request",
    "Summary Request",
    "Clarification snippet of code",
    "Summary Feedback",
    "Summary Request",
    "Request formatting output change",
    "Code Explanation",
    "Task Clarification",
    "Code Explanation",
    "Summary Request",
    "Summary Request",
    "Summary Request",
    "Code Copied for In-depth Summary",
    "Summary Revision",
    "Code Copied for In-depth Summary",
    "Summary Request",
    "Summary Revision",
    "Summary Request",
    "Task Clarification",
    "Summary Request",
    "Summary Request",
    "Code Explaination Request",
    "Summary Revision",
    "Summary Revision",
    "Clarification snippet of code",
    "Summary Request",
    "Python Syntax Explanatation",
    "Code Copied for in-depth summary",
    "Summary Revision",
    "Summary Revision",
    "Code Explanation",
    "Summary Revision",
    "Code Explanation",
    "Summary Revision",
    "Code Explanation",
    "Summary Request",
    "Summary Request",
    "Summary Revision",
    "Summary Revision",
    "Code Explanation",
    "Code Explanation",
    "Summary Revision",
    "Summary Request",
    "Summary Request",
    "Code Copied for in-depth summary",
    "Summary Request",
    "Summary Request",
    "Code Snippet Explanation",
    "summary Feedback",
    "Summary Revision",
    "Summary Request",
    "Code Copied for in-depth summary",
    "Code Copied for in-depth summary",
    "Code Copied for in-depth summary",
    "Summary Feedback",
    "Summary Revision",
    "Python Syntax Explanation",
    "Code Explanation",
    "Clarification Snippetof Code",
    "Clarification Snippet of Code",
    "Summary Request",
    "Code Explanation",
    "Summary Request",
    "Summary Feedback",
    "Summary Feedback",
    "Code Explanation",
    "Summary Request",
    "Summary Request",
    "Summary Feedback",
    "Summary Request",
    "Summary Request",
    "Code Explanation",
    "Code Explanation",
    "Code Explanation",
    "Clarification Snippet of Code"
]

annotator_2 = [
    "Clarification snippet of code",
    "Clarification snippet of code",
    "Clarification snippet of code",
    "Clarification snippet of code",
    "Summary Request",
    "Clarification snippet of code",
    "Summary Request",
    "Summary Request",
    "Clarification snippet of code",
    "Summary Feedback",
    "Summary Request",
    "Request formatting output change",
    "Code Explanation",
    "Task Clarification",
    "Code Explanation",
    "Summary Request",
    "Summary Request",
    "Summary Request",
    "Code Explanation",
    "Summary Revision",
    "Code Explanation",
    "Summary Request",
    "Code Generation from Summary",
    "Summary Request",
    "Clarification snippet of code",
    "Summary Request",
    "Code Explanation",
    "Code Explanation",
    "Summary Revision",
    "Summary Revision",
    "Clarification snippet of code",
    "Summary Request",
    "syntax clarification",
    "Code Explanation",
    "Summary Revision",
    "Summary Revision",
    "Code Explanation",
    "Summary Feedback",
    "Clarification snippet of code",
    "Summary Revision",
    "Clarification snippet of code",
    "Summary Request",
    "Summary Request",
    "Summary Request",
    "Summary Feedback",
    "Summary Feedback",
    "Code Explanation",
    "Code Explanation",
    "Summary Revision",
    "Summary Request",
    "Summary Request",
    "Code Explanation",
    "Summary Request",
    "Summary Request",
    "Clarification snippet of code",
    "Summary Feedback/Evaluation",
    "Summary Revision",
    "Request formatting output change",
    "Summary Request",
    "Code Explanation",
    "Code Explanation",
    "Summary Feedback/Evaluation",
    "Summary Revision",
    "Python Syntax Explanation",
    "Code Explanation",
    "Clarification snippet of code",
    "Code Explanation",
    "Summary Request",
    "Code Explanation",
    "Summary Feedback/Evaluation",
    "Summary Feedback/Evaluation",
    "Code Explanation",
    "Code Explanation",
    "Summary Request"
    "Summary Request",
    "Summary Feedback/Evaluation",
    "Summary Request",
    "Request formatting output change",
    "Code Explanation",
    "Code Explanation",
    "Code Explanation",
    "Clarification snippet of code"
]
print("Annotator 1:", len(annotator_1))
print("Annotator 2:", len(annotator_2))

kappa = cohen_kappa_score(annotator_1, annotator_2)
print(f"Cohen's Kappa: {kappa:.2f}")

len_annotator_1 = len(annotator_1)
len_annotator_2 = len(annotator_2)

len_annotator_1, len_annotator_2

